
### 订阅一个topic, cid为a
http://localhost:8765/mq/sub?t=cn.ipman.test&cid=a


### 发送一个消息
POST http://localhost:8765/mq/send?t=cn.ipman.test&cid=a
Content-Type: application/json

{
  "body":"{\"id\":5,\"item\":\"item0\",\"price\":0.0}"
}

### 接收一个消息
GET http://localhost:8765/mq/receive?t=cn.ipman.test&cid=a


### ack
GET http://localhost:8765/mq/ack?t=cn.ipman.test&cid=a&offset=4